### PR TITLE
Use pragma

### PR DESCRIPTION
**Pull request by redianthus**
Hi,

@FooB4r, @emersion, please, be smart like @GiulioGargantini, use `#pragma once`.

### CODE REVIEW

**Review by emersion — APPROVED** [review]
I want to be smart.

**Comment by emersion** [comment]
LGTM, thanks!

**Comment by redianthus** [comment]
Can I get some ECTS for this ?

**Comment by emersion** [comment]
Go ask Sylvain for it. ;)

**Comment by redianthus** [comment]
Dddddddddddddddddddd

**Pull request merged**
