### PR TITLE
add msys2/mingw support

### PR DESCRIPTION
**Pull request by delthas**

### CODE REVIEW

**Comment by emersion** [comment]
I'd like to merge this, unfortunately we have to support cmake 3.2 because some people have older versions in their repos. :/

**Comment by emersion** [comment]
Maybe the first commit can be slightly modified, without these Qt CMake changes?

**Review by emersion — APPROVED** [review]
It seems that `COMPONENTS` is available since CMake 3.0: https://cmake.org/cmake/help/v3.0/command/find_package.html

**Comment by delthas** [comment]
Oh yeah, my bad, CMake 3.7 only changed [the example file for the better way to find Qt components](https://gitlab.kitware.com/cmake/cmake/merge_requests/226/commits), but the feature was there before.

**Pull request merged**
